### ISSUE TITLE
NoSuchMethodError in Pet

### ISSUE THREAD

**Issue by kaytlinm** [haciim/study_buddy_2020#27]
Error whenever trustCheck() or moodCheck() called. Tests commented out of PetTests in order for build to complete.

`java.lang.NoSuchMethodError: android.util.Log.i(Ljava/lang/String;Ljava/lang/String;)I 
        at studyBuddy.DataManager.load(DataManager.java:77)
	at studyBuddy.Pet.getWPA(Pet.java:214)
	at studyBuddy.Pet.trustCheck(Pet.java:256)
	at PetTests.trustTest(PetTests.java:72)`

**Comment by andrewcalimlim** [comment]
Hmm, not really sure why this exception would be thrown because both `trustCheck()` and `moodCheck()` are public methods of the Pet class file

**Comment by andrewcalimlim** [comment]
Yeah in the Pet test file `spark.trustCheck()` and `spock.moodCheck()` should both work

**Comment by kaytlinm** [comment]
Looks like it's running into issues within `DataManager.java:77` not sure what that entails. @Tomi-Tanaka  any ideas?

**Comment by andrewcalimlim** [comment]
I load the session history as `List<Session> sessions = DataManager.load(List.class);`, I remember he said he might be changing the load method though in a meeting or two ago

**Comment by Tomi-Tanaka** [comment]
I think the issue is with the Log method, for some reason it won't work when running the unit tests

**Comment by andrewcalimlim** [comment]
Oh it might be because the test file is only importing the Pet class, explicitly import the Data Manager/Session classes too then?

**Comment by kaytlinm** [comment]
I changed it to import all of studdybuddy and same exception

**Comment by kaytlinm** [comment]
Is the Log method running into issues elsewhere in tests?

**Comment by Tomi-Tanaka** [comment]
I think we should just modify the pet class so that it doesn't have to load sessions directly through data manager and instead just takes a list of sessions for calculating mood/trust. Then we wouldn't have to worry about the log method not working and we'd be able to do more robust testing on the trust/mood methods, since we'd be able to test them on different datasets

**Comment by kaytlinm** [comment]
Seems to fix the no such method call but running into JUnit issues with testing methods not mocked (?) seems its not worth the extent of changes to test 2 small methods. going to merge your changes @Tomi-Tanaka and my updates to Pet but just not explicitly test mood & trust checks
