### ISSUE TITLE
NullPointer in worstTrustCheck()

### ISSUE THREAD

**Issue by kaytlinm** [haciim/study_buddy_2020#28]
When worstTrustCheck() called during testing, commented out of testing for build purposes

`java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at studyBuddy.Pet.worstTrustCheck(Pet.java:407)
	at PetTests.trustTest(PetTests.java:104)`

**Comment by andrewcalimlim** [comment]
Oh whoops, I set the conditional to check if the Date object lastDAWT wasn't initialized (Pet has not reached the lowest trust level yet) to `if (lastDAWT != null)` instead of `if (lastDAWT == null)`.

**Comment by kaytlinm** [comment]
Fixed and committed to pet_updates branch
