### ISSUE TITLE
App crashes when checking session history

### ISSUE THREAD

**Issue by Tomi-Tanaka** [haciim/study_buddy_2020#35]
My virtual device's date is set to January 1st 2020. When I try to check session history after finishing a session the app crashes with the error `java.time.DateTimeException: Invalid value for MonthOfYear: 0`

**Comment by hingler** [comment]
turns out we can in fact just add 1 to it. The "Month" class has its own set of constants for each month and it starts with January at 0. Just a disagreement between the methods we were using, it looks like.

**Comment by hingler** [comment]
[more info](https://developer.android.com/reference/java/time/Month#of(int))

Month.of expects a value from 1 to 12, but getMonth returns a value from 0 to 11. that sucks
