### ISSUE TITLE
Changing system clock during session causes timer to update but is not reflected in session history

### ISSUE THREAD

**Issue by Tomi-Tanaka** [haciim/study_buddy_2020#44]
When changing the system clock mid-session (for example, moving it ahead by two hours), the timer shows that the session has indeed been active for the expected amount of time (two hours). After finishing the session and checking the session history, however, the time that was shown on the timer is not what is recorded. I think that what ends up being recorded is the actual time that the session ran, independent of the system time.

**Comment by hingler** [comment]
I have no idea why the session record is reporting the way it does -- it has something to do with the way that the end time is being set, but copying that method and moving it over to the endSession callback does not fix the output on the end session screen. I've tried to make the output consistent at least, so both the sessionHistory and the endSession view will output the same value.

There are still conditions in which the former sessionHistory method produces an incorrect result, so hopefully this is OK.
